server:
  port: 8081

spring:
  application:
    name: lists-service

jwt:
  secret: acme-risk-analysis-secret-key-for-internal-communication

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan:
    - com.acme.lists.infrastructure.controller
  paths-to-match:
    - /**

logging:
  level:
    com.acme.lists: DEBUG

