server:
  port: 8080

spring:
  application:
    name: risk-analysis-service

services:
  lists:
    url: http://lists-service:8081
  decision-engine:
    url: http://decision-engine-service:8082

risk:
  score:
    low:
      max: 399
    medium:
      max: 699

jwt:
  secret: acme-risk-analysis-secret-key-for-internal-communication
  expiration: 3600000

# Configuração do Swagger/OpenAPI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan:
    - com.acme.risk.analysis.infrastructure.controller
  paths-to-match:
    - /**

logging:
  level:
    com.acme.risk.analysis: DEBUG
    org.springframework.web.client: DEBUG

